### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by ErikBooij** [shootphp/shoot#16]
Was trying to configure Shoot according to the README, only to find out the `Installer` isn't available yet in the latest release.

Could you tag a new release? :)

**Comment by EngineerAirhead** [comment]
+1 Would love to play more with this

**Comment by victorwelling** [comment]
[Done](https://github.com/shootphp/shoot/releases/tag/v2.0.0) 👍

**Comment by ErikBooij** [comment]
> +1 Would love to play more with this

Because it never too late to reply with

*That's what she said*
